spring:
  thymeleaf:
    check-template-location: false
  application:
    name: finance_manager_plan_backend
  datasource:
    url: jdbc:postgresql://ep-damp-band-a15ee45l-pooler.ap-southeast-1.aws.neon.tech/finance_manager?sslmode=require
    username: neondb_owner
    password: *************
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nqanh120503@gmail.com
    password: ************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true

jwt:
  signerKey: "tIpVTNnjWmJ+nIwbqvcFMdikQPxERxhtiGBnbhGtJSj2LG0126wKHw/Dro7bie6D"
  valid-duration: 172800
  refreshable-duration: 604800
